### ISSUE TITLE
Readme in english

### ISSUE THREAD

**Issue by mehrazi** [novioleo/FOTS#10]
@novioleo Hi, thanks for sharing your work.
can you provide an English readme?
thanks in advance.

**Comment by novioleo** [comment]
@mehrdadazizi72 soon. 3-5 days

**Comment by novioleo** [comment]
@mehrdadazizi72 
i have pushed the [readme](./README_english.md). draft version for you.

**Comment by mehrazi** [comment]
@novioleo thanks :)
