### ISSUE TITLE
What the runtime environment is?

### ISSUE THREAD

**Issue by learn01one** [novioleo/FOTS#16]
你好，可以提供下运行环境版本吗？
pytorch
python
谢谢。

**Comment by novioleo** [comment]
python 3.6.5
pytorch 1.0.1.post2




------------------ 原始邮件 ------------------
发件人: "learn01one"<notifications@github.com>; 
发送时间: 2019年7月12日(星期五) 晚上7:46
收件人: "novioleo/FOTS"<FOTS@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [novioleo/FOTS] 运行环境询问 (#16)




你好，可以提供下运行环境版本吗？
 pytorch
 python
 谢谢。
 
&mdash;
