### ISSUE TITLE
eval.py: _Py_ZeroStruct undefined

### ISSUE THREAD

**Issue by RyanRTJJ** [novioleo/FOTS#8]
Hi @novioleo, I made an English README for you, you might want to use it :)
[README2.txt](https://github.com/novioleo/FOTS/files/3222440/README2.txt)

Training seems to be going fine, except that my epoch loss is always 'inf':
```
    epoch          : 2
    loss           : inf
    det_loss       : 0.017797884885644308
    rec_loss       : inf
    precious       : 0.9999588631264025
    recall         : 0.9999588631264025
    hmean          : 0.9999588631264025
    val_loss       : 0.0
    val_det_loss   : 0.0
    val_rec_loss   : 0.0
    val_precious   : 0.0
    val_recall     : 0.0
    val_hmean      : 0.0
```
even if my batch loss is fine: 
`Train Epoch: 3 [12/12033 (0%)] Loss: 4.605296 Detection Loss: 0.011160 Recognition Loss:4.594136`

Is this normal, or did I configure something wrong somewhere?

Also, when I run eval.py, I keep getting this error message:
```
Traceback (most recent call last):
  File "eval.py", line 129, in <module>
    main(args)
  File "eval.py", line 99, in main
    strLabelConverter(getattr(common_str,args.keys)))
  File "/home/Ryan1/FOTS/utils/bbox.py", line 327, in predict
    score_map, geo_map, (preds, lengths), boxes, pred_mapping, indices = model.forward(im_resized)
  File "/home/Ryan1/FOTS/model/model.py", line 154, in forward
    pred_boxes, pred_mapping = _compute_boxes(score_map, geo_map)
  File "/home/Ryan1/FOTS/model/model.py", line 120, in _compute_boxes
    detected_boxes, _ = Toolbox.detect(score_map=cur_score, geo_map=cur_geometry, timer=timer)
  File "/home/Ryan1/FOTS/utils/bbox.py", line 196, in detect
    boxes = lanms.merge_quadrangle_n9(boxes.astype('float32'), nms_thres)
  File "/home/Ryan1/FOTS/utils/lanms/__init__.py", line 12, in merge_quadrangle_n9
    from .adaptor import merge_quadrangle_n9 as nms_impl
ImportError: /home/Ryan1/FOTS/utils/lanms/adaptor.so: undefined symbol: _Py_ZeroStruct
```

**This is my Make in utils/lanms**
```
CXXFLAGS = -I include  -std=c++11 -O3 -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7  -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes


LDFLAGS = $(shell python3-config --ldflags)

DEPS = lanms.h $(shell find include -xtype f)
CXX_SOURCES = adaptor.cpp include/clipper/clipper.cpp

LIB_SO = adaptor.so

$(LIB_SO): $(CXX_SOURCES) $(DEPS)
	$(CXX) -o $@ $(CXXFLAGS) $(LDFLAGS) $(CXX_SOURCES) --shared -fPIC

clean:
	rm -rf $(LIB_SO)
```
I've searched on Google, but it seems that this problem is specific to EAST. Couldn't find anything applicable to this code. Thanks for your help!

**Comment by novioleo** [comment]
@RyanRTJJ thks for your work.
1. in the train progress ,the recognize loss cannot be inf.can u share me more detail about your debug info?
2. lanms must compile with python3,but the header you include is python2.7....
recommand you follow my Makefile...it's very easy.

**Comment by RyanRTJJ** [comment]
1. Here's an example batch that ended with inf.

```
/home/Ryan1/FOTS/data/MSCOCO/annotations/COCO_train2014_000000336289.txt
execution begins
else taken
polys len, texts len: 2 2
passed  COCO_train2014_000000336289.jpg [[[0. 0. 0.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 1. 1.]
  [0. 0. 2.]
  [0. 0. 2.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]] ['ATOMIC' 'SEck']
/home/Ryan1/FOTS/data/MSCOCO/annotations/COCO_train2014_000000252340.txt
execution begins
else taken
polys len, texts len: 14 14
passed  COCO_train2014_000000252340.jpg [[[254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 ...

 [[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]

 [[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]

 [[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]] ['stop' 'approaching' 'LANDING ' 'aircraft' 'aircraft' 'cross'
 'prosecuted' 'violators' 'when' 'ZONE' 'not' 'are' 'do' 'stop']
/home/Ryan1/FOTS/data/MSCOCO/annotations/COCO_train2014_000000508870.txt
execution begins
if taken                                                            # (np.random.rand() < background_ratio)
failed  None None None None                       # Failed to meet some assert statement, re-do
/home/Ryan1/FOTS/data/MSCOCO/annotations/COCO_train2014_000000508870.txt
execution begins
else taken
polys len, texts len: 6 6
passed  COCO_train2014_000000508870.jpg [[[195. 201. 191.]
  [ 78.  71.  55.]
  [190. 188. 177.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]

 [[199. 206. 194.]
  [ 84.  78.  63.]
  [165. 161. 148.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]

 [[203. 211. 196.]
  [ 90.  84.  71.]
  [139. 135. 119.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]

 ...

 [[ 46.  35.  33.]
  [ 46.  36.  34.]
  [ 46.  36.  34.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]

 [[ 41.  32.  28.]
  [ 40.  31.  27.]
  [ 40.  31.  26.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]

 [[ 45.  36.  31.]
  [ 47.  38.  33.]
  [ 47.  39.  33.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]] ['94' 'OC' '514.545.4333' '' 'AMMOET' 'MAMMOET']
inf,, 0.036181215196847916,,inf
Train Epoch: 1 [3972/12033 (33%)] Loss: inf Detection Loss: 0.036181 Recognition Loss:inf
```

2. Yeah, I reverted back python3.6. It's able to execute. Though, I'm not sure what output this is: 
```
0it [00:00, ?it/s]
1it [00:00,  1.15it/s]
```
I am getting the output image though, which is good. Is there a way to get annotation data - polygon coordinates + label?

**Comment by novioleo** [comment]
@RyanRTJJ 
```
0it [00:00, ?it/s]
1it [00:00,  1.15it/s]
```
this info produced by tqdm.


and do you mean how to get the annotationed data with tool?
i use labelme,vott etc..

**Comment by RyanRTJJ** [comment]
@novioleo 

Oh I mean when I run eval.py, where does the prediction polygon / label get written?

**Comment by novioleo** [comment]
it will plot on the corespond result image.


 
---Original---

**Comment by RyanRTJJ** [comment]
Ok, I will extract it myself later. For now, I'm still trying to solve the inf loss problem. I used pysnooper on
`def _train_epoch(self)` in **trainer/trainer.py**, and narrowed down the error location. This is the output:

```
    15:16:07.422041 line        98                 det_loss, reg_loss = self.loss(score_map,
    15:16:07.488283 line        99                                                pred_score_map if pred_score_map is not None else score_map,
    15:16:07.554251 line       100                                                geo_map,
    15:16:07.620275 line       101                                                pred_geo_map if pred_geo_map is not None else geo_map,
    15:16:07.688543 line       102                                                recog,
    15:16:07.754839 line       103                                                pred_recog,
    15:16:07.821190 line       104                                                training_mask)
    Modified var:.. det_loss = tensor(0.0057, device='cuda:0', grad_fn=<AddBackward0>)
    Modified var:.. reg_loss = tensor(inf, device='cuda:0', grad_fn=<MeanBackward1>)
    15:16:07.888295 line       105                 loss = det_loss + reg_loss
    Modified var:.. loss = tensor(inf, device='cuda:0', grad_fn=<AddBackward0>)
    15:16:07.955204 line       106                 loss.backward()
    15:16:08.446663 line       107                 self.optimizer.step()
    15:16:08.545477 line       109                 total_loss += loss.item()
    Modified var:.. total_loss = inf
    15:16:08.613686 line       110                 total_det_loss += det_loss.item()
    Modified var:.. total_det_loss = 0.06601216783747077
    15:16:08.682342 line       114                 total_rec_loss += reg_loss.item()
    Modified var:.. total_rec_loss = inf
```

So it looks like the self.loss function is causing the problem, but I can't seem to find the function definition, where is it? I also tried finding the forward pass function, but I can't either. Thanks for the help

**Comment by novioleo** [comment]
@RyanRTJJ i will solve this problem as fast as i could .

**Comment by RyanRTJJ** [comment]
@novioleo Thank you so much :D

**Comment by novioleo** [comment]
@RyanRTJJ 
you can get some info from the refer issue:
https://github.com/baidu-research/warp-ctc/issues/23

**Comment by ongcj** [comment]
Hi @RyanRTJJ  @novioleo 

I also have the infinite recognition loss issue. And also, i noticed that my precious, recall and hmean seems very low as compared to yours, and negative value on val_loss and val_rec_loss. Is this normal? 
Thanks.

    epoch          : 2
    loss           : inf
    det_loss       : 0.019610022264642056
    rec_loss       : inf
    precious       : 0.0018082673912389045
    recall         : 0.0018082673912389045
    hmean          : 0.0018082673912389047
    val_loss       : -1.400883362653028
    val_det_loss   : 0.023725635739729592
    val_rec_loss   : -1.4246089983927577
    val_precious   : 0.0
    val_recall     : 0.0
    val_hmean      : 0.0

**Comment by novioleo** [comment]
check your dataset and charset.


 
---Original---

**Comment by RyanRTJJ** [comment]
Hi @novioleo (Thanks for the link) @ongcj,

My understanding of the inf loss problem is that the probability is too tiny to be contained as floating point numbers in memory, hence the CTC loss = -log(probability) is equivalent to -log(0) = inf. If you're wondering how the probability can decrease to such a small number (I'm not sure what this limit is, it depends on python's float type and size), it's because,
probability(correct word) = probability(correct letter at position t) * probability(correct letter at position t+1) * ...
You can see how fast my probability decreases with number of time steps. I have 93 characters, hence the probability decreases by a magnitude of 2 per time step. Randomized weights also cause certain characters to have an extremely low probability. I believe this will improve with training over time, and you'll see fewer infs, but I'm not sure as I've only been able to run this code for 15 epochs so far. 

**I've tried** going to right where the CTC loss is produced, and added a catch.
``` pseudo-code:
if loss==inf:
    loss=4.53
```
4.53 is because that's equivalent to -log(base e)(1/93). The math is wrong and this is generally a bad idea because it's hard to assume a mean loss for a word of variable length, even if you do know the length. I'm also not sure if my understanding of the math is correct, so I'm just going to ignore this inf problem for now and hope for the best (LOL).

One way to quickly 'fix' it is to decrease number of labels / characters in your charset. This doesn't entirely address the issue, but if you can do with fewer labels, your model will be easier to train too.

As for your low precious, recall, and hmean, I agree with TL that your charset probably has something wrong with it. Can u paste the 'keys' u are using here? If u think that's not the problem, then did you install pretrainedmodels library? I think my values are high because the detection part is basically a pretrained model running in the back-end, so the detection part seems to be doing rather well.

**Comment by novioleo** [comment]
@RyanRTJJ you are right.you need to ignore the inf problem.

**Comment by ongcj** [comment]
Hi @RyanRTJJ, 
Currently my precious, recall and hmean looks like this. 
```
    epoch          : 453
    loss           : 2.4419258351617015
    det_loss       : 0.01093589951297347
    rec_loss       : 2.430989939841866
    precious       : 0.11151650876861115
    recall         : 0.11151650876861115
    hmean          : 0.11151650876861115
    val_loss       : 14.888946675413631
    val_det_loss   : 5.272431064066232
    val_rec_loss   : 9.616515611347399
    val_precious   : 0.0043859649122807015
    val_recall     : 0.0043859649122807015
    val_hmean      : 0.0043859649122807015
```
And the keys is "custom_1" from common_str,

`custom_1 = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-.'
`

for some reason, it is still very low. I really appreciate both you and @novioleo 's help. Thanks

**Comment by novioleo** [comment]
@ongcj i found this error in these days.mainly because i don't have enough time to adapt the icdar2015~~so that, there are some error occur and the precious is too low.
you can try to use your own dataset,and there is neither '###' or '*' or other useless label.

i can archieve a very satisfactory result use mydataset which look like the scenario 1...

**Comment by ongcj** [comment]
@novioleo so for the ICDAR2015 dataset, I just need to remove all annotation that contains transcript for ###? 

suppose that I am using myowndataset in config.json, I make changes to load_annotation in datautils under dataloader?

**Comment by novioleo** [comment]
@ongcj almost right.

**Comment by ongcj** [comment]
Hi @novioleo, this is the load_annotation. May i know what is text_tags? 

```
def load_annoataion(p):
    '''
    load annotation from the text file
    :param p:
    :return:
    '''
    text_polys = []
    text_tags = []
    texts = []
    print("loading annotation")
    if not os.path.exists(p):
        return np.array(text_polys, dtype=np.float32)
    with open(p, 'r') as f:
        reader = csv.reader(f)
        for line in reader:
            label = line[-1].strip()
            # strip BOM. \ufeff for python3,  \xef\xbb\bf for python2
            
            if label == '*' or label == '###' or label == '':
                #text_tags.append(True)
                print("Ignore ###")
            else:
                line = [i.strip('\ufeff').strip('\xef\xbb\xbf') for i in line]

                x1, y1, x2, y2, x3, y3, x4, y4 = list(map(float, line[:8]))
                text_polys.append([[x1, y1], [x2, y2], [x3, y3], [x4, y4]])
                texts.append(label)  
                text_tags.append(False)
        return np.array(text_polys, dtype=np.float32), np.array(texts), np.array(text_tags, dtype=np.bool)

```

**Comment by novioleo** [comment]
tag to filter.


 
---Original---

**Comment by ongcj** [comment]
@novioleo is there any more places i should take note of? Thanks

**Comment by novioleo** [comment]
@ongcj fots good at short text sequence.

**Comment by ongcj** [comment]
@novioleo May i know what config did you used to train ICDAR2015? About how many epoch? Thanks

**Comment by novioleo** [comment]
@ongcj just the same as you.and it performed poorly.

**Comment by RyanRTJJ** [comment]
@ongcj 

Editing of annotations is also done when special characters are encountered. They are all in `utils/eval_tools/icdar2015/eval.py`.

Do a Ctrl-F search for all functions that contain the variable `SPECIAL_CHARACTERS` or `specialCharacters`, and see if they are affecting your annotations.

**Comment by ongcj** [comment]
@RyanRTJJ Ah I see. Will check that out. Thanks. How are your training with COCO text going?

**Comment by RyanRTJJ** [comment]
@ongcj I just opened a new issue to discuss training. Head over there to see!
